### ISSUE TITLE
zamani neden disardan aldin?

### ISSUE THREAD

**Issue by ugorur** [hadeyici/blockChainPHP#2]
https://github.com/hadeyici/blockChainPHP/blob/b902574b4c6208d67d99a297e9b012bb766f7ad5/blockchain.php#L13

**Comment by hadeyici** [comment]
incelediğim örneklerde ve kendime referans aldığım örnekte ([burada](https://github.com/SavjeeTutorials/SavjeeCoin/blob/master/src/main.js)) dışardan alıyordu, aynı yaklaşımı kullandım. Özellikle bir amacı var mı bilmiyorum. Bu konuda herhangi bir bilgiye rastlamadım.
